baseURL = "http://beingadityak.com/"
languageCode = "en-us"
title = "aditya krishnakumar"
theme = "goa"
author = "aditya krishnakumar"
publishdir = "docs"

enableRobotsTXT = "true"

[params]
    author = "aditya krishnakumar"
    intro = "devops consultant - multi-cloud and cloud native"
    description = "devops consultant. previously bcg and other service-based companies."
    dateformat = "Jan 2, 2006"
    authorimage = "aditya_krishnakumar.jpeg"

[params.social]
    github = "beingadityak"
    instagram = "beingadityak"
    twitter = "beingadityak_"
    email = "consult@beingadityak.com"
    linkedin = "beingadityak"
    gitlab = "beingadityak"

[[menu.main]]
    name = "blog"
    weight = 100
    url = "https://blog.beingadityak.com"
[[menu.main]]
    name = "resume"
    weight = 200
    url = "https://resume.beingadityak.com"